# #7.12 verifyEmail Test

## verifyEmail() - should verify email

### 테스트 할 코드

users.service.ts

```ts
async verifyEmail(code: string): Promise<VerifyEmailOutput> {
    try {
      const verification = await this.verifications.findOne(
        { code },
        { relations: ['user'] },
      );
      if (verification) {
        verification.user.verified = true;
        await this.users.save(verification.user);
        await this.verifications.delete(verification.id);
        return {
          ok: true,
        };
      }

      ...
```

### mocking

users.service.spec.ts

```ts
const mockedVerification = {
  id: 1,
  code: 'code',
  user: { verified: false },
};
verificationRepository.findOne.mockResolvedValue(mockedVerification);
```

### expect

users.service.spec.ts

```ts
const result = await service.verifyEmail('');

expect(verificationRepository.findOne).toHaveBeenCalledTimes(1);
expect(verificationRepository.findOne).toHaveBeenCalledWith(
  expect.any(Object),
  expect.any(Object),
);

expect(usersRepository.save).toHaveBeenCalledTimes(1);
expect(usersRepository.save).toHaveBeenCalledWith({ verified: true });

expect(verificationRepository.delete).toHaveBeenCalledTimes(1);
expect(verificationRepository.delete).toHaveBeenCalledWith(
  mockedVerification.id,
);
expect(result).toEqual({ ok: true });
```

- `verification.user.verified = true;` 코드를 통해 `user`의 `verified`부분이 `false`에서 `true`로 바뀌어서 `save()` 인자로 들어갔는지 확인

## verifyEmail() - should fail on verification not found

users.service.spec.ts

```ts
verificationRepository.findOne.mockResolvedValue(undefined);
const result = await service.verifyEmail('');
expect(result).toEqual({ ok: false, error: '잘못된 인증코드입니다.' });
```

## verifyEmail() - should fail on exception

users.service.spec.ts

```ts
verificationRepository.findOne.mockRejectedValue(new Error());
const result = await service.verifyEmail('');
expect(result).toEqual({ ok: false, error: '잘못된 접근입니다.' });
```
